# Requires install of nightly rustfmt
# rustup +nightly component add rustfmt
# To use add +nightly to Rust Format: Extra Args in vscode, or equivalent in your editor of choice
edition = "2018"
imports_granularity = "Module"
merge_derives = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true